# Generated by Django 4.1.7 on 2023-03-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=10)),
                ('Beneficiario', models.CharField(max_length=200)),
                ('Concepto', models.CharField(max_length=200)),
                ('Bank', models.CharField(max_length=200)),
                ('IBAN', models.CharField(max_length=24)),
                ('BIC', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone', models.FloatField(verbose_name=9)),
            ],
        ),
    ]
